#!/bin/sh
#
# Post installation script for Jsign
#

set -e

# Create the symbolic link to the executable script
chmod +x /usr/share/jsign/jsign.sh
ln --force -s /usr/share/jsign/jsign.sh /usr/bin/jsign
